# Generated by Django 2.2.4 on 2019-09-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_login', '0002_auto_20190831_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='Time',
            field=models.FloatField(default=0),
        ),
    ]
